services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:3335
    volumes:
      - .:/usr/src/app
    ports:
      - "3335:3335"
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  pgadmin_data: