services:
  web:
    build: .
    ports:
      - "3333:3333"
    command: sh -c "python manage.py runserver 0.0.0.0:3333"
    volumes:
      - .:/usr/src/app
    env_file: .env
    restart: always
  db:
    image: postgres:14.7
    expose:
      - "5432"
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    restart: always
