version: '3.10'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8989
    volumes:
      - .:/usr/src/app
    ports:
      - "8989:8989"
    networks:
      - db_network
      
  # cuda:
  #   image: nvidia/cuda:11.7.1-devel-ubuntu22.04
  #   shm_size: '23g'
  #   command: nvidia-smi
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #             - driver: nvidia
  #               count: 1
  #               capabilities: [ gpu ]

networks:
  db_network:
    driver: bridge

volumes:
  pgadmin_data: